name: "Test: model check examples (`make tlc`)"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # ensure all examples work
    - run: nix-shell -p tlaplus --run 'make tlc'
